name: react-unit-tests
discover: vitest list --filesOnly
run: |
  yarn --silent test --listTestsoutputs:
  junit: react/junit/junit.xml
options:
  dynamic-test-splitting: true
  test-impact-analysis: false