name: react-unit-tests
discover: yarn --silent test --listTests
run: JEST_JUNIT_OUTPUT_FILE="<< outputs.junit >>" yarn test --runInBand --reporters=jest-junit --bail << test.atoms >>
outputs:
  junit: react/junit/junit.xml
options:
  dynamic-test-splitting: true
  test-impact-analysis: false